spring:
  application:
    name: discovery-client
logging:
  pattern:
    console: "%d{yy-MM-dd E HH:mm:ss.SSS} %highlight(%-5p) ${PID} --- %clr([%8.15t]){cyan} %highlight(%logger{36}){blue} : %m %n"
  level:
    org.springframework.web: INFO
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  profiles: zone1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/,http://localhost:8890/eureka/
server:
  port: ${PORT:8071}
---
spring:
  profiles: zone2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/,http://localhost:8890/eureka/,http://localhost:8888/eureka/
server:
  port: ${PORT:8072}
---
spring:
  profiles: zone3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8890/eureka/,http://localhost:8888/eureka/,http://localhost:8889/eureka/
server:
  port: ${PORT:8073}